language: python
dist: focal

arch:
 - amd64
 - ppc64le
sudo: false

addons:
  apt:
    packages:
      - libproj-dev
      - libeccodes-dev

env:
  global:
    - DEPENDS="numpy pyproj"

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

notifications:
  email: false

before_install:
  - pip install $DEPENDS

install:
  - python setup.py install

script:
  - python test.py
