language: python
dist: focal

arch:
 - amd64
 - ppc64le
sudo: false

addons:
  apt:
    packages:
      - libgrib-api-dev

env:
  global:
    - DEPENDS="numpy pyproj"

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

notifications:
  email: false

before_install:
  - sudo apt-get install libproj-dev proj-bin
  - pip install $DEPENDS
  - sudo apt-get install libeccodes-dev

install:
  - python setup.py build
  - python setup.py install

script:
  - python test.py
